import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const img = (category: string, file: string) => `/images/products/${category}/${file}`;

async function main() {
  console.log('Starting product seeding from Materials...');

  const cats = await prisma.category.findMany();
  const byType = (type: string) => cats.find(c => c.type === type);
  const bySlug = (slug: string) => cats.find(c => c.slug === slug);

  await prisma.productLocation.deleteMany();
  await prisma.wishlistItem.deleteMany();
  await prisma.product.deleteMany();
  await prisma.dealer.deleteMany();
  console.log('Cleared existing products');

  // ========== SEEDS ==========
  const riceCat = bySlug('rice-seeds');
  const maizeCat = bySlug('maize-seeds');
  const vegCat = bySlug('vegetable-seeds');
  const fruitCat = bySlug('fruit-seeds');

  // ========== PESTICIDES ==========
  const pestCat = bySlug('pesticides');

  // ========== MACHINERY ==========
  const tractorCat = bySlug('tractors');
  const harvestCat = bySlug('harvesting-machinery');
  const rotavatorCat = bySlug('rotavators');

  // ========== LUBRICANTS ==========
  const lubeCat = bySlug('lubricants-oils');

  // ========== MICRONUTRIENTS ==========
  const microCat = bySlug('micronutrients');

  const products = [
    // --- SEEDS ---
    {
      name: 'Hybrid Maize — Corns Oct',
      nameBn: 'হাইব্রিড ভুট্টা — কর্নস অক্টোবর',
      slug: 'hybrid-maize-corns-oct',
      description: 'High-yielding hybrid maize variety with excellent germination rate. Developed for Bangladesh climate. Maturity: 100-110 days. Average yield: 10-12 t/ha. Suitable for Kharif and Rabi seasons.',
      descriptionBn: 'উচ্চ অঙ্কুরোদগম হার সহ উচ্চ ফলনশীল হাইব্রিড ভুট্টা জাত। বাংলাদেশের জলবায়ুর জন্য উন্নত। পরিপক্বতা: ১০০-১১০ দিন। গড় ফলন: ১০-১২ টন/হেক্টর।',
      price: 450, priceUnit: 'KG', categoryId: maizeCat?.id,
      featured: true, inStock: true,
      images: [img('seeds', 'Corns-Oct.png')],
      specs: { yield: '10-12 t/ha', maturity: '100-110 days', purity: '98%', season: 'Kharif & Rabi' },
    },
    {
      name: 'Hybrid Rice — Hybrid Rice Nov',
      nameBn: 'হাইব্রিড ধান',
      slug: 'hybrid-rice-nov',
      description: 'Premium hybrid rice variety developed for Boro season. Excellent grain quality with long slender grains. Blast resistant. Average yield: 7.5-8.5 t/ha.',
      descriptionBn: 'বোরো মৌসুমের জন্য উন্নত প্রিমিয়াম হাইব্রিড ধানের জাত। চমৎকার দানার গুণাগুণ। ব্লাস্ট প্রতিরোধী।',
      price: 140, priceUnit: 'KG', categoryId: riceCat?.id,
      featured: true, inStock: true,
      images: [img('seeds', 'Hybrid-Rice-Nov.png')],
      specs: { yield: '7.5-8.5 t/ha', maturity: '140-145 days', grain: 'Long slender', disease: 'Blast resistant' },
    },
    {
      name: 'Agnila Hybrid Rice — Jan',
      nameBn: 'অগ্নিলা হাইব্রিড ধান',
      slug: 'agnila-hybrid-rice',
      description: 'Early maturing hybrid rice variety. Suitable for early Boro and Aus seasons. Good grain quality with high milling output.',
      descriptionBn: 'অল্প সময়ে পরিপক্ক হাইব্রিড ধানের জাত। প্রারম্ভিক বোরো এবং আউস মৌসুমের জন্য উপযুক্ত।',
      price: 135, priceUnit: 'KG', categoryId: riceCat?.id,
      featured: false, inStock: true,
      images: [img('seeds', 'Agnila-Jan.png')],
      specs: { yield: '7-8 t/ha', maturity: '135-140 days', season: 'Early Boro & Aus' },
    },
    {
      name: 'Captain Hybrid Rice — June',
      nameBn: 'ক্যাপ্টেন হাইব্রিড ধান',
      slug: 'captain-hybrid-rice',
      description: 'High-yielding Aman season hybrid rice. Tolerant to submergence and diseases. Excellent for rain-fed areas.',
      descriptionBn: 'আমান মৌসুমের উচ্চ ফলনশীল হাইব্রিড ধান। নিমজ্জন এবং রোগ সহনশীল।',
      price: 145, priceUnit: 'KG', categoryId: riceCat?.id,
      featured: true, inStock: true,
      images: [img('seeds', 'Captain-June.png')],
      specs: { yield: '7-8 t/ha', maturity: '145-150 days', tolerance: 'Submergence tolerant', season: 'Aman' },
    },
    {
      name: 'Green Magic Maize — Aug',
      nameBn: 'গ্রিন ম্যাজিক ভুট্টা',
      slug: 'green-magic-maize',
      description: 'Super hybrid maize variety with excellent cob size and grain fill. High shelling percentage. Suitable for both grain and fodder.',
      descriptionBn: 'চমৎকার শসার আকার এবং দানা পূরণ সহ সুপার হাইব্রিড ভুট্টা জাত।',
      price: 480, priceUnit: 'KG', categoryId: maizeCat?.id,
      featured: false, inStock: true,
      images: [img('seeds', 'Green-Magic-Aug.png')],
      specs: { yield: '11-13 t/ha', maturity: '105-115 days', usage: 'Grain & Fodder' },
    },
    {
      name: 'Green Queen Maize — Sep',
      nameBn: 'গ্রিন কুইন ভুট্টা',
      slug: 'green-queen-maize',
      description: 'Premium quality hybrid maize with high nutritional value. Excellent for poultry feed industry. High starch content.',
      descriptionBn: 'উচ্চ পুষ্টিমান সহ প্রিমিয়াম কোয়ালিটি হাইব্রিড ভুট্টা। পোল্ট্রি ফিড শিল্পের জন্য চমৎকার।',
      price: 460, priceUnit: 'KG', categoryId: maizeCat?.id,
      featured: false, inStock: true,
      images: [img('seeds', 'Green-Queen-Sep.png')],
      specs: { yield: '10-12 t/ha', maturity: '100-110 days', starch: 'High', usage: 'Poultry feed' },
    },
    {
      name: 'King Kumra — Hybrid Pumpkin',
      nameBn: 'কিং কুমড়া — হাইব্রিড মিষ্টি কুমড়া',
      slug: 'king-kumra-hybrid-pumpkin',
      description: 'Hybrid sweet pumpkin variety. Fruits weigh 2.5-3 kg each. Dark green skin with light yellow patches. Bright orange flesh. Very sweet taste. Harvest: 80-85 days. Yield: 12-13 tons/acre.',
      descriptionBn: 'হাইব্রিড মিষ্টি কুমড়া জাত। প্রতিটি ফলের ওজন ২.৫-৩ কেজি। গাঢ় সবুজ খোসা। খুব মিষ্টি স্বাদ।',
      price: 110, priceUnit: 'PIECE', categoryId: vegCat?.id,
      featured: true, inStock: true,
      images: [img('seeds', 'King-Kumra.png')],
      specs: { fruit_weight: '2.5-3 kg', maturity: '80-85 days', yield: '12-13 tons/acre', color: 'Dark green', flesh: 'Bright orange' },
    },
    {
      name: 'Millenium Rice — Feb',
      nameBn: 'মিলেনিয়াম ধান',
      slug: 'millenium-rice',
      description: 'Super premium hybrid rice with millennium-class yield potential. Extra-long grains with excellent cooking quality.',
      descriptionBn: 'মিলেনিয়াম-শ্রেণির ফলন সম্ভাবনা সহ সুপার প্রিমিয়াম হাইব্রিড ধান।',
      price: 150, priceUnit: 'KG', categoryId: riceCat?.id,
      featured: true, inStock: true,
      images: [img('seeds', 'Millenium-Feb.png')],
      specs: { yield: '8-9 t/ha', maturity: '145-150 days', grain: 'Extra-long', quality: 'Premium cooking' },
    },
    {
      name: 'Ononna Hybrid Rice — May',
      nameBn: 'অনন্যা হাইব্রিড ধান',
      slug: 'ononna-hybrid-rice',
      description: 'Popular hybrid rice variety among Bangladeshi farmers. Consistent yield performance. Good tolerance to pests and diseases.',
      descriptionBn: 'বাংলাদেশী কৃষকদের মধ্যে জনপ্রিয় হাইব্রিড ধানের জাত। ধারাবাহিক ফলন।',
      price: 140, priceUnit: 'KG', categoryId: riceCat?.id,
      featured: false, inStock: true,
      images: [img('seeds', 'Ononna-May.png')],
      specs: { yield: '7-8 t/ha', maturity: '140-148 days', tolerance: 'Pest & disease tolerant' },
    },
    {
      name: 'Pilot Hybrid Rice — Mar',
      nameBn: 'পাইলট হাইব্রিড ধান',
      slug: 'pilot-hybrid-rice',
      description: 'Pilot class hybrid rice for demonstration-scale farming. Excellent uniformity and grain quality.',
      descriptionBn: 'প্রদর্শনী-স্কেল চাষের জন্য পাইলট শ্রেণির হাইব্রিড ধান। চমৎকার সমতা।',
      price: 138, priceUnit: 'KG', categoryId: riceCat?.id,
      featured: false, inStock: true,
      images: [img('seeds', 'Pilot-Mar.png')],
      specs: { yield: '7-8.5 t/ha', maturity: '140-145 days', uniformity: 'Excellent' },
    },
    {
      name: 'SQ King Hybrid Rice — July',
      nameBn: 'এসকিউ কিং হাইব্রিড ধান',
      slug: 'sq-king-hybrid-rice',
      description: 'Flagship hybrid rice variety from SQ Agriculture. Premium quality with outstanding yield. King of hybrid rice in Bangladesh.',
      descriptionBn: 'এসকিউ এগ্রিকালচারের ফ্ল্যাগশিপ হাইব্রিড ধানের জাত। অসাধারণ ফলন।',
      price: 155, priceUnit: 'KG', categoryId: riceCat?.id,
      featured: true, inStock: true,
      images: [img('seeds', 'SQ-King-July.png')],
      specs: { yield: '8-10 t/ha', maturity: '140-150 days', grain: 'Premium long', quality: 'Flagship' },
    },
    // --- PESTICIDES ---
    {
      name: 'Anithrin 10 EC — Insecticide',
      nameBn: 'অ্যানিথ্রিন ১০ ইসি',
      slug: 'anithrin-10-ec',
      description: 'Broad-spectrum insecticide containing active ingredient for effective pest control. 400 ml pack. Controls aphids, jassids, thrips and whiteflies.',
      descriptionBn: 'কার্যকর কীট নিয়ন্ত্রণের জন্য ব্রড-স্পেকট্রাম কীটনাশক। ৪০০ মিলি প্যাক।',
      price: 350, priceUnit: 'LITRE', categoryId: pestCat?.id,
      featured: true, inStock: true,
      images: [img('pesticides', '1.-Anithrin-10-EC---400-ml.png')],
      specs: { formulation: 'EC 10%', pack_size: '400 ml', target: 'Aphids, Jassids, Thrips, Whiteflies' },
    },
    {
      name: 'Keyatin 1.8 EC — Insecticide',
      nameBn: 'কেয়াটিন ১.৮ ইসি',
      slug: 'keyatin-18-ec',
      description: 'Systemic insecticide for controlling sucking pests. Effective against mites and insects. 400 ml pack.',
      descriptionBn: 'চোষক কীট নিয়ন্ত্রণের জন্য সিস্টেমিক কীটনাশক। মাইট এবং পোকার বিরুদ্ধে কার্যকর।',
      price: 380, priceUnit: 'LITRE', categoryId: pestCat?.id,
      featured: false, inStock: true,
      images: [img('pesticides', '2.-Keyatin-1.8-EC---400-ml.png')],
      specs: { formulation: 'EC 1.8%', pack_size: '400 ml', target: 'Mites, Sucking pests' },
    },
    {
      name: 'Evic Plus 5 EC — Insecticide',
      nameBn: 'ইভিক প্লাস ৫ ইসি',
      slug: 'evic-plus-5-ec',
      description: 'Powerful insecticide with enhanced formula. 500 ml pack. Controls stem borers, fruit borers and leaf folders.',
      descriptionBn: 'বর্ধিত ফর্মুলা সহ শক্তিশালী কীটনাশক। ৫০০ মিলি প্যাক।',
      price: 420, priceUnit: 'LITRE', categoryId: pestCat?.id,
      featured: false, inStock: true,
      images: [img('pesticides', '3.-Evic-Plus-5-EC---500-ml.png')],
      specs: { formulation: 'EC 5%', pack_size: '500 ml', target: 'Stem borers, Fruit borers' },
    },
    {
      name: 'Imulin 20 SL — Insecticide',
      nameBn: 'ইমুলিন ২০ এসএল',
      slug: 'imulin-20-sl',
      description: 'Systemic insecticide with Imidacloprid active ingredient. 500 ml pack. Excellent for controlling sucking pests in rice, vegetables and fruits.',
      descriptionBn: 'ইমিডাক্লোপ্রিড সক্রিয় উপাদান সহ সিস্টেমিক কীটনাশক। ৫০০ মিলি প্যাক।',
      price: 450, priceUnit: 'LITRE', categoryId: pestCat?.id,
      featured: true, inStock: true,
      images: [img('pesticides', '4.-Imulin-20-SL---500-ml.png')],
      specs: { formulation: 'SL 20%', pack_size: '500 ml', target: 'Sucking pests (Rice, Vegetables)' },
    },
    {
      name: 'Keratin 4 EC — Insecticide',
      nameBn: 'কেরাটিন ৪ ইসি',
      slug: 'keratin-4-ec',
      description: 'Concentrated insecticide formulation. 50 ml pack. Effective against a wide range of agricultural pests.',
      descriptionBn: 'ঘনীভূত কীটনাশক ফর্মুলেশন। ৫০ মিলি প্যাক।',
      price: 180, priceUnit: 'ML', categoryId: pestCat?.id,
      featured: false, inStock: true,
      images: [img('pesticides', '5.-Keratin-4-EC---50-ml.png')],
      specs: { formulation: 'EC 4%', pack_size: '50 ml', target: 'Broad-spectrum' },
    },
    {
      name: 'Keyazate 5 WDG — Insecticide',
      nameBn: 'কেয়াজেট ৫ ডব্লিউডিজি',
      slug: 'keyazate-5-wdg',
      description: 'Water dispersible granule insecticide. 100 gm pack. Easy to use with excellent dispersion properties.',
      descriptionBn: 'ওয়াটার ডিসপার্সিবল গ্রানিউল কীটনাশক। ১০০ গ্রাম প্যাক।',
      price: 280, priceUnit: 'GRAM', categoryId: pestCat?.id,
      featured: false, inStock: true,
      images: [img('pesticides', '6.-Keyazate-5-WDG---100-gm.png')],
      specs: { formulation: 'WDG 5%', pack_size: '100 gm', target: 'Broad-spectrum' },
    },
    {
      name: 'Keyadin 6 WDG — Insecticide',
      nameBn: 'কেয়াডিন ৬ ডব্লিউডিজি',
      slug: 'keyadin-6-wdg',
      description: 'Advanced water dispersible granule formulation. 10 gm pack. Quick action against pests.',
      descriptionBn: 'উন্নত ওয়াটার ডিসপার্সিবল গ্রানিউল ফর্মুলেশন। ১০ গ্রাম প্যাক।',
      price: 120, priceUnit: 'GRAM', categoryId: pestCat?.id,
      featured: false, inStock: true,
      images: [img('pesticides', '7.-Keyadin-6-WDG---10-gm.png')],
      specs: { formulation: 'WDG 6%', pack_size: '10 gm', action: 'Quick action' },
    },
    {
      name: 'Keyaprid 6 WDG — Insecticide',
      nameBn: 'কেয়াপ্রিড ৬ ডব্লিউডিজি',
      slug: 'keyaprid-6-wdg',
      description: 'Effective water dispersible granule insecticide. 10 gm pack. Controls rice planthoppers and leafhoppers.',
      descriptionBn: 'কার্যকর ওয়াটার ডিসপার্সিবল গ্রানিউল কীটনাশক। ১০ গ্রাম প্যাক।',
      price: 130, priceUnit: 'GRAM', categoryId: pestCat?.id,
      featured: false, inStock: true,
      images: [img('pesticides', '8.-Keyaprid-6-WDG---10-gm.png')],
      specs: { formulation: 'WDG 6%', pack_size: '10 gm', target: 'Planthoppers, Leafhoppers' },
    },
    {
      name: 'Fachlor 18 WP — Insecticide',
      nameBn: 'ফ্যাক্লোর ১৮ ডব্লিউপি',
      slug: 'fachlor-18-wp',
      description: 'Wettable powder insecticide. 50 gm pack. Broad-spectrum control of chewing and sucking insects.',
      descriptionBn: 'ওয়েটেবল পাউডার কীটনাশক। ৫০ গ্রাম প্যাক।',
      price: 200, priceUnit: 'GRAM', categoryId: pestCat?.id,
      featured: false, inStock: true,
      images: [img('pesticides', '9.-Fachlor-18-WP---50-gm.png')],
      specs: { formulation: 'WP 18%', pack_size: '50 gm', target: 'Chewing & Sucking insects' },
    },
    {
      name: 'Mantasha 40 WDG — Fungicide',
      nameBn: 'মন্তাশা ৪০ ডব্লিউডিজি',
      slug: 'mantasha-40-wdg',
      description: 'High-performance fungicide in water dispersible granule form. 10 gm pack. Controls fungal diseases in rice, vegetables and fruits.',
      descriptionBn: 'ওয়াটার ডিসপার্সিবল গ্রানিউল আকারে উচ্চ-কার্যক্ষমতা সম্পন্ন ছত্রাকনাশক। ১০ গ্রাম প্যাক।',
      price: 160, priceUnit: 'GRAM', categoryId: pestCat?.id,
      featured: true, inStock: true,
      images: [img('pesticides', '10.-Mantasha-40-WDG---10-gm.png')],
      specs: { formulation: 'WDG 40%', pack_size: '10 gm', target: 'Fungal diseases' },
    },
    {
      name: 'Kazebin 50 WDG — Fungicide',
      nameBn: 'কাজেবিন ৫০ ডব্লিউডিজি',
      slug: 'kazebin-50-wdg',
      description: 'Powerful fungicide for crop protection. 10 gm pack. Prevents and controls blast, blight and leaf spot diseases.',
      descriptionBn: 'ফসল সুরক্ষার জন্য শক্তিশালী ছত্রাকনাশক। ১০ গ্রাম প্যাক।',
      price: 180, priceUnit: 'GRAM', categoryId: pestCat?.id,
      featured: false, inStock: true,
      images: [img('pesticides', '11.-Kazebin-50-WDG---10-gm.png')],
      specs: { formulation: 'WDG 50%', pack_size: '10 gm', target: 'Blast, Blight, Leaf spot' },
    },
    {
      name: 'Flash Hit 70 WDG — Fungicide',
      nameBn: 'ফ্লাশ হিট ৭০ ডব্লিউডিজি',
      slug: 'flash-hit-70-wdg',
      description: 'Fast-acting fungicide with 70% active ingredient. 50 gm pack. Quick control of fungal outbreaks.',
      descriptionBn: '৭০% সক্রিয় উপাদান সহ দ্রুত-কার্যকর ছত্রাকনাশক। ৫০ গ্রাম প্যাক।',
      price: 350, priceUnit: 'GRAM', categoryId: pestCat?.id,
      featured: false, inStock: true,
      images: [img('pesticides', '13.-Flash-Hit-70-WDG---50-gm.png')],
      specs: { formulation: 'WDG 70%', pack_size: '50 gm', action: 'Fast-acting' },
    },
    {
      name: 'Keyatov 75 WG — Fungicide',
      nameBn: 'কেয়াটভ ৭৫ ডব্লিউজি',
      slug: 'keyatov-75-wg',
      description: 'Premium fungicide with 75% active ingredient. 50 gm pack. Excellent for preventive and curative disease control.',
      descriptionBn: '৭৫% সক্রিয় উপাদান সহ প্রিমিয়াম ছত্রাকনাশক। ৫০ গ্রাম প্যাক।',
      price: 380, priceUnit: 'GRAM', categoryId: pestCat?.id,
      featured: true, inStock: true,
      images: [img('pesticides', '14.-Keyatov-75-WG---50-gm.png')],
      specs: { formulation: 'WG 75%', pack_size: '50 gm', usage: 'Preventive & Curative' },
    },
    {
      name: 'Keyaton 95 SP — Fungicide',
      nameBn: 'কেয়াটন ৯৫ এসপি',
      slug: 'keyaton-95-sp',
      description: 'Highly concentrated soluble powder fungicide. 50 gm pack. Maximum disease protection with minimal dosage.',
      descriptionBn: 'অত্যন্ত ঘনীভূত দ্রবণীয় পাউডার ছত্রাকনাশক। ৫০ গ্রাম প্যাক।',
      price: 420, priceUnit: 'GRAM', categoryId: pestCat?.id,
      featured: false, inStock: true,
      images: [img('pesticides', '15.-Keyaton-95-SP---50-gm.png')],
      specs: { formulation: 'SP 95%', pack_size: '50 gm', dosage: 'Minimal' },
    },
    {
      name: 'Muntaha 70 WDG — Fungicide',
      nameBn: 'মুনতাহা ৭০ ডব্লিউডিজি',
      slug: 'muntaha-70-wdg',
      description: 'Broad-spectrum fungicide for major crop diseases. 10 gm pack. Effective against powdery mildew and rust.',
      descriptionBn: 'প্রধান ফসলের রোগের জন্য ব্রড-স্পেকট্রাম ছত্রাকনাশক। ১০ গ্রাম প্যাক।',
      price: 150, priceUnit: 'GRAM', categoryId: pestCat?.id,
      featured: false, inStock: true,
      images: [img('pesticides', '16.-Muntaha-70-WDG---10-gm.png')],
      specs: { formulation: 'WDG 70%', pack_size: '10 gm', target: 'Powdery mildew, Rust' },
    },
    {
      name: 'Thot 80 WG — Fungicide',
      nameBn: 'থট ৮০ ডব্লিউজি',
      slug: 'thot-80-wg',
      description: 'Powerful fungicide for agricultural use. 1 kg pack. Long-lasting protection against fungal pathogens.',
      descriptionBn: 'কৃষি কাজের জন্য শক্তিশালী ছত্রাকনাশক। ১ কেজি প্যাক।',
      price: 850, priceUnit: 'KG', categoryId: pestCat?.id,
      featured: false, inStock: true,
      images: [img('pesticides', '17.-Thot-80-WG---1-kg.png')],
      specs: { formulation: 'WG 80%', pack_size: '1 kg', duration: 'Long-lasting' },
    },
    {
      name: 'Manconil 72 WP — Fungicide',
      nameBn: 'ম্যানকোনিল ৭২ ডব্লিউপি',
      slug: 'manconil-72-wp',
      description: 'Multi-purpose wettable powder fungicide. Controls a wide range of fungal diseases in various crops.',
      descriptionBn: 'বহু-উদ্দেশ্য ওয়েটেবল পাউডার ছত্রাকনাশক। বিভিন্ন ফসলের বিভিন্ন ছত্রাক রোগ নিয়ন্ত্রণ করে।',
      price: 320, priceUnit: 'GRAM', categoryId: pestCat?.id,
      featured: false, inStock: true,
      images: [img('pesticides', '18.-Manconil-72-WP.png')],
      specs: { formulation: 'WP 72%', target: 'Broad-spectrum fungal diseases' },
    },
    {
      name: 'Nikizeb 80 WP — Fungicide',
      nameBn: 'নিকিজেব ৮০ ডব্লিউপি',
      slug: 'nikizeb-80-wp',
      description: 'High-content wettable powder fungicide. Effective preventive fungicide for healthy crop growth.',
      descriptionBn: 'উচ্চ-ঘনত্বের ওয়েটেবল পাউডার ছত্রাকনাশক। স্বাস্থ্যকর ফসলের জন্য কার্যকর প্রতিরোধক।',
      price: 340, priceUnit: 'GRAM', categoryId: pestCat?.id,
      featured: false, inStock: true,
      images: [img('pesticides', '19.-Nikizeb-80-WP.png')],
      specs: { formulation: 'WP 80%', usage: 'Preventive' },
    },
    {
      name: 'SQ Super Darma — Herbicide',
      nameBn: 'এসকিউ সুপার দারমা',
      slug: 'sq-super-darma',
      description: 'Powerful herbicide for effective weed control in rice fields. Broad-spectrum weed management.',
      descriptionBn: 'ধানক্ষেত্রে কার্যকর আগাছা নিয়ন্ত্রণের জন্য শক্তিশালী আগাছানাশক।',
      price: 250, priceUnit: 'UNIT', categoryId: pestCat?.id,
      featured: false, inStock: true,
      images: [img('pesticides', '20.-SQ-Super-Darma.png')],
      specs: { type: 'Herbicide', target: 'Broad-spectrum weeds', crop: 'Rice' },
    },
    {
      name: 'Dizizol 10 G — Insecticide',
      nameBn: 'ডাইজিজোল ১০ জি',
      slug: 'dizizol-10-g',
      description: 'Granular insecticide for soil application. 10 kg pack. Controls soil-borne insects and root pests.',
      descriptionBn: 'মাটি প্রয়োগের জন্য গ্রানিউলার কীটনাশক। ১০ কেজি প্যাক।',
      price: 950, priceUnit: 'KG', categoryId: pestCat?.id,
      featured: false, inStock: true,
      images: [img('pesticides', '21.-Dizizol-10-G.png')],
      specs: { formulation: 'Granular 10%', pack_size: '10 kg', target: 'Soil-borne insects' },
    },
    {
      name: 'Eros Gold 30.75 DF — Fungicide',
      nameBn: 'ইরোস গোল্ড ৩০.৭৫ ডিএফ',
      slug: 'eros-gold-30-75-df',
      description: 'Premium dry flowable fungicide with 30.75% active ingredient. Advanced formulation for easy mixing and application.',
      descriptionBn: '৩০.৭৫% সক্রিয় উপাদান সহ প্রিমিয়াম ড্রাই ফ্লোয়েবল ছত্রাকনাশক।',
      price: 550, priceUnit: 'GRAM', categoryId: pestCat?.id,
      featured: true, inStock: true,
      images: [img('pesticides', '22.-Eros-Gold-30.75-DF.jpg')],
      specs: { formulation: 'DF 30.75%', type: 'Fungicide', feature: 'Advanced formulation' },
    },
    // --- TRACTORS ---
    {
      name: 'New Holland TT55 Tractor',
      nameBn: 'নিউ হল্যান্ড TT55 ট্রাক্টর',
      slug: 'new-holland-tt55',
      description: '55 HP utility tractor with 3-cylinder Iveco diesel engine. 8F+2R transmission. Available in 2WD and 4WD. Ideal for small to medium farms. Lift capacity: 1800 kg. Fuel tank: 89L.',
      descriptionBn: '৫৫ HP ইউটিলিটি ট্রাক্টর। ছোট থেকে মাঝারি খামারের জন্য আদর্শ।',
      price: 750000, priceUnit: 'UNIT', categoryId: tractorCat?.id,
      featured: true, inStock: true, hidePrice: true,
      images: [img('tractors', '476167125_599249506362451_1470294131761454851_n.jpg')],
      specs: { power: '55 HP', engine: 'Iveco 2.9L 3-cyl Diesel', transmission: '8F+2R', drive: '2WD/4WD', lift_capacity: '1800 kg' },
    },
    {
      name: 'New Holland TT75 Tractor',
      nameBn: 'নিউ হল্যান্ড TT75 ট্রাক্টর',
      slug: 'new-holland-tt75',
      description: '75 HP utility tractor. 4-cylinder engine. Higher lift capacity for heavy implements. Perfect for medium to large farms.',
      descriptionBn: '৭৫ HP ইউটিলিটি ট্রাক্টর। মাঝারি থেকে বড় খামারের জন্য উপযুক্ত।',
      price: 950000, priceUnit: 'UNIT', categoryId: tractorCat?.id,
      featured: true, inStock: true, hidePrice: true,
      images: [img('tractors', 'new-holland-tractor-cover.jpg')],
      specs: { power: '75 HP', engine: '4-cyl Diesel', transmission: '8F+2R', drive: '2WD/4WD' },
    },
    // --- HARVESTERS ---
    {
      name: 'SQ Etian Combine Harvester',
      nameBn: 'এসকিউ ইটিয়ান কম্বাইন হারভেস্টার',
      slug: 'sq-etian-combine-harvester',
      description: 'SQ branded combine harvester for efficient rice and wheat harvesting. Reduces harvest time and labor cost. Features advanced threshing and cleaning system.',
      descriptionBn: 'দক্ষ ধান ও গম কাটার জন্য এসকিউ ব্র্যান্ডেড কম্বাইন হারভেস্টার।',
      price: 2500000, priceUnit: 'UNIT', categoryId: harvestCat?.id,
      featured: true, inStock: true, hidePrice: true,
      images: [img('harvesters', 'Etian-SQTE.png'), img('harvesters', 'harvestor.jpg')],
      specs: { type: 'Combine Harvester', brand: 'SQ Etian', usage: 'Rice & Wheat', cutting_width: '4 ft' },
    },
    {
      name: 'Fieldking Power Tiller',
      nameBn: 'ফিল্ডকিং পাওয়ার টিলার',
      slug: 'fieldking-power-tiller',
      description: 'Fieldking brand power tiller for seed bed preparation. Suitable for small and medium farms. Fuel-efficient diesel engine.',
      descriptionBn: 'বীজতলা তৈরির জন্য ফিল্ডকিং ব্র্যান্ডের পাওয়ার টিলার।',
      price: 185000, priceUnit: 'UNIT', categoryId: rotavatorCat?.id,
      featured: false, inStock: true, hidePrice: true,
      images: [img('harvesters', 'Fieldking.png')],
      specs: { brand: 'Fieldking', type: 'Power Tiller', usage: 'Seed bed preparation' },
    },
    {
      name: 'SQ Rotavator',
      nameBn: 'এসকিউ রোটাভেটর',
      slug: 'sq-rotavator',
      description: 'Heavy-duty rotavator for soil preparation. Compatible with 50-75 HP tractors. Efficient tilling with adjustable depth. Saves time and fuel.',
      descriptionBn: 'মাটি প্রস্তুতির জন্য ভারী-ডিউটি রোটাভেটর। ৫০-৭৫ HP ট্রাক্টরের সাথে সামঞ্জস্যপূর্ণ।',
      price: 95000, priceUnit: 'UNIT', categoryId: rotavatorCat?.id,
      featured: true, inStock: true, hidePrice: true,
      images: [img('harvesters', 'Rotavator.png')],
      specs: { type: 'Rotavator', compatible: '50-75 HP Tractor', width: '5-6 ft', tilling_depth: 'Adjustable' },
    },
    {
      name: 'Zoomlion Combine Harvester',
      nameBn: 'জুমলিয়ন কম্বাইন হারভেস্টার',
      slug: 'zoomlion-combine-harvester',
      description: 'Chinese brand combine harvester. Reliable performance for rice harvesting. Good after-sales service network in Bangladesh.',
      descriptionBn: 'চীনা ব্র্যান্ডের কম্বাইন হারভেস্টার। ধান কাটার জন্য নির্ভরযোগ্য পারফরম্যান্স।',
      price: 2200000, priceUnit: 'UNIT', categoryId: harvestCat?.id,
      featured: false, inStock: true, hidePrice: true,
      images: [img('harvesters', 'Zoomlion.png')],
      specs: { brand: 'Zoomlion', type: 'Combine Harvester', usage: 'Rice harvesting' },
    },
    {
      name: 'TCT 3230 Power Tiller',
      nameBn: 'টিসিটি ৩২৩০ পাওয়ার টিলার',
      slug: 'tct-3230-power-tiller',
      description: 'TCT brand power tiller with 12HP engine. Reliable and easy to maintain. Suitable for Bangladeshi soil conditions.',
      descriptionBn: 'টিসিটি ব্র্যান্ডের পাওয়ার টিলার। বাংলাদেশের মাটির জন্য উপযুক্ত।',
      price: 175000, priceUnit: 'UNIT', categoryId: rotavatorCat?.id,
      featured: false, inStock: true, hidePrice: true,
      images: [img('harvesters', 'Tct-3230.png')],
      specs: { brand: 'TCT', power: '12 HP', type: 'Power Tiller' },
    },
    {
      name: 'SQ TT3.50 Tractor',
      nameBn: 'এসকিউ টিটি৩.৫০ ট্রাক্টর',
      slug: 'sq-tt3-50-tractor',
      description: 'Compact tractor model for small farm operations. Versatile for multiple agricultural tasks including tilling, hauling and spraying.',
      descriptionBn: 'ছোট খামার কাজের জন্য কম্প্যাক্ট ট্রাক্টর মডেল।',
      price: 550000, priceUnit: 'UNIT', categoryId: tractorCat?.id,
      featured: false, inStock: true, hidePrice: true,
      images: [img('harvesters', 'TT3.50.png')],
      specs: { model: 'TT3.50', type: 'Compact Tractor', usage: 'Multi-purpose' },
    },
    {
      name: 'SQ TT47 Tractor',
      nameBn: 'এসকিউ টিটি৪৭ ট্রাক্টর',
      slug: 'sq-tt47-tractor',
      description: 'Mid-range tractor model (47 HP). Ideal for medium farms. Good fuel efficiency and reliable performance.',
      descriptionBn: 'মিড-রেঞ্জ ট্রাক্টর মডেল (৪৭ HP)। মাঝারি খামারের জন্য আদর্শ।',
      price: 650000, priceUnit: 'UNIT', categoryId: tractorCat?.id,
      featured: false, inStock: true, hidePrice: true,
      images: [img('harvesters', 'TT47.png')],
      specs: { model: 'TT47', power: '47 HP', type: 'Utility Tractor' },
    },
    {
      name: 'SQ TT70 Tractor',
      nameBn: 'এসকিউ টিটি৭০ ট্রাক্টর',
      slug: 'sq-tt70-tractor',
      description: 'Powerful 70 HP tractor for heavy farm operations. Suitable for large-scale farming. Excellent torque and pull strength.',
      descriptionBn: 'ভারী খামার কাজের জন্য শক্তিশালী ৭০ HP ট্রাক্টর।',
      price: 880000, priceUnit: 'UNIT', categoryId: tractorCat?.id,
      featured: true, inStock: true, hidePrice: true,
      images: [img('harvesters', 'TT70.png')],
      specs: { model: 'TT70', power: '70 HP', type: 'Heavy-duty Tractor' },
    },
    // --- MICRONUTRIENTS ---
    {
      name: 'Boron Max — Micronutrient',
      nameBn: 'বোরন ম্যাক্স',
      slug: 'boron-max',
      description: 'Boron micronutrient fertilizer. 500 gm pack. Essential for flowering, fruit set and seed development. Prevents hollow heart in fruits.',
      descriptionBn: 'বোরন মাইক্রোনিউট্রিয়েন্ট সার। ৫০০ গ্রাম প্যাক।',
      price: 180, priceUnit: 'GRAM', categoryId: microCat?.id,
      featured: false, inStock: true,
      images: [img('micronutrients', '1.-Boron-Max---500-gm.png')],
      specs: { nutrient: 'Boron', pack_size: '500 gm', benefit: 'Flowering & fruit set' },
    },
    {
      name: 'Monohydrate — Zinc Sulphate',
      nameBn: 'মনোহাইড্রেট — জিংক সালফেট',
      slug: 'monohydrate-zinc',
      description: 'Zinc sulphate monohydrate micronutrient. 1 kg pack. Corrects zinc deficiency in crops. Essential for enzyme activation and growth regulation.',
      descriptionBn: 'জিংক সালফেট মনোহাইড্রেট মাইক্রোনিউট্রিয়েন্ট। ১ কেজি প্যাক।',
      price: 220, priceUnit: 'KG', categoryId: microCat?.id,
      featured: false, inStock: true,
      images: [img('micronutrients', '3.-Monohydrate---1-kg.png')],
      specs: { nutrient: 'Zinc Sulphate Monohydrate', pack_size: '1 kg', benefit: 'Corrects Zn deficiency' },
    },
    {
      name: 'Spray Potash — Liquid',
      nameBn: 'স্প্রে পটাশ',
      slug: 'spray-potash',
      description: 'Liquid potassium fertilizer for foliar application. 250 gm pack. Quick absorption through leaves. Improves fruit quality and disease resistance.',
      descriptionBn: 'পাতা প্রয়োগের জন্য তরল পটাশিয়াম সার। ২৫০ গ্রাম প্যাক।',
      price: 150, priceUnit: 'GRAM', categoryId: microCat?.id,
      featured: false, inStock: true,
      images: [img('micronutrients', '4.-Spray-Potash---250-gm.png')],
      specs: { nutrient: 'Potassium (Liquid)', pack_size: '250 gm', application: 'Foliar spray' },
    },
    {
      name: 'Tiger Zinc — EDTA Chelated',
      nameBn: 'টাইগার জিংক',
      slug: 'tiger-zinc',
      description: 'EDTA chelated zinc micronutrient. 25 gm pack. Highly available form of zinc for plants. Corrects deficiency quickly.',
      descriptionBn: 'ইডিটিএ চেলেটেড জিংক মাইক্রোনিউট্রিয়েন্ট। ২৫ গ্রাম প্যাক।',
      price: 80, priceUnit: 'GRAM', categoryId: microCat?.id,
      featured: false, inStock: true,
      images: [img('micronutrients', '5.-Tiger-Zinc---25-gm.png')],
      specs: { nutrient: 'EDTA Zinc', pack_size: '25 gm', form: 'Chelated' },
    },
    {
      name: 'Turbo Gypsum — Calcium & Sulphur',
      nameBn: 'টার্বো জিপসাম',
      slug: 'turbo-gypsum',
      description: 'Gypsum-based soil amendment. 10 kg pack. Provides calcium and sulphur. Improves soil structure and reduces salinity.',
      descriptionBn: 'জিপসাম-ভিত্তিক মাটি সংশোধনকারী। ১০ কেজি প্যাক।',
      price: 320, priceUnit: 'KG', categoryId: microCat?.id,
      featured: false, inStock: true,
      images: [img('micronutrients', '6.-Turbo-Gypsum---10-kg.png')],
      specs: { nutrient: 'Calcium & Sulphur', pack_size: '10 kg', benefit: 'Soil structure improvement' },
    },
    {
      name: 'Super Folon — Liquid Fertilizer',
      nameBn: 'সুপার ফলন',
      slug: 'super-folon',
      description: 'Liquid foliar fertilizer with multiple micronutrients. 100 ml pack. Boosts crop yield and quality.',
      descriptionBn: 'একাধিক মাইক্রোনিউট্রিয়েন্ট সহ তরল পাতা সার। ১০০ মিলি প্যাক।',
      price: 120, priceUnit: 'ML', categoryId: microCat?.id,
      featured: true, inStock: true,
      images: [img('micronutrients', '7.-Super-Folon---100-ml.png')],
      specs: { type: 'Liquid Foliar Fertilizer', pack_size: '100 ml', benefit: 'Yield booster' },
    },
    {
      name: 'Pango — Liquid NPK',
      nameBn: 'প্যাঙ্গো',
      slug: 'pango-liquid-npk',
      description: 'Balanced liquid NPK fertilizer with micronutrients. 1 litre pack. Complete plant nutrition for all growth stages.',
      descriptionBn: 'মাইক্রোনিউট্রিয়েন্ট সহ সুষম তরল এনপিকে সার। ১ লিটার প্যাক।',
      price: 450, priceUnit: 'LITRE', categoryId: microCat?.id,
      featured: true, inStock: true,
      images: [img('micronutrients', '8.-Pango---1-ltr.png')],
      specs: { type: 'Liquid NPK', pack_size: '1 litre', npk_ratio: 'Balanced' },
    },
    // --- LUBRICANTS ---
    {
      name: 'GearTech Extra — Gear Oil',
      nameBn: 'গিয়ারটেক এক্সট্রা',
      slug: 'geartech-extra',
      description: 'Premium gear oil for agricultural machinery transmissions. High viscosity protection. Suitable for tractor gearboxes and differentials.',
      descriptionBn: 'কৃষি যন্ত্রপাতি ট্রান্সমিশনের জন্য প্রিমিয়াম গিয়ার অয়েল।',
      price: 650, priceUnit: 'LITRE', categoryId: lubeCat?.id,
      featured: false, inStock: true,
      images: [img('lubricants', 'GearTech-Extra.png')],
      specs: { type: 'Gear Oil', usage: 'Transmission & Differentials', viscosity: 'High' },
    },
    {
      name: 'Harvester Pro Engine Oil',
      nameBn: 'হারভেস্টার প্রো ইঞ্জিন অয়েল',
      slug: 'harvester-pro-engine-oil',
      description: 'Specialized engine oil for combine harvesters. Protects against wear under heavy loads. Extends engine life.',
      descriptionBn: 'কম্বাইন হারভেস্টারের জন্য বিশেষায়িত ইঞ্জিন অয়েল।',
      price: 720, priceUnit: 'LITRE', categoryId: lubeCat?.id,
      featured: true, inStock: true,
      images: [img('lubricants', 'Harvester-Pro-Engine-Oil.png')],
      specs: { type: 'Engine Oil', usage: 'Combine Harvesters', benefit: 'Wear protection' },
    },
    {
      name: 'Hydro AW68 — Hydraulic Oil',
      nameBn: 'হাইড্রো AW68',
      slug: 'hydro-aw68',
      description: 'Anti-wear hydraulic oil for agricultural machinery. AW68 grade. Suitable for hydraulic systems of tractors and implements.',
      descriptionBn: 'কৃষি যন্ত্রপাতির জন্য অ্যান্টি-ওয়্যার হাইড্রোলিক অয়েল।',
      price: 580, priceUnit: 'LITRE', categoryId: lubeCat?.id,
      featured: false, inStock: true,
      images: [img('lubricants', 'Hydro-AW68.png')],
      specs: { type: 'Hydraulic Oil', grade: 'AW68', usage: 'Tractor hydraulics' },
    },
    {
      name: 'Tractor Pro Engine Oil',
      nameBn: 'ট্রাক্টর প্রো ইঞ্জিন অয়েল',
      slug: 'tractor-pro-engine-oil',
      description: 'High-performance engine oil specifically formulated for diesel tractor engines. Excellent thermal stability and anti-wear protection.',
      descriptionBn: 'ডিজেল ট্রাক্টর ইঞ্জিনের জন্য বিশেষভাবে তৈরি উচ্চ-কার্যক্ষমতা সম্পন্ন ইঞ্জিন অয়েল।',
      price: 680, priceUnit: 'LITRE', categoryId: lubeCat?.id,
      featured: true, inStock: true,
      images: [img('lubricants', 'Tractor-Pro-Engine-Oil.png')],
      specs: { type: 'Engine Oil', usage: 'Diesel Tractors', benefit: 'Thermal stability' },
    },
    {
      name: 'Tractor Transmission Oil',
      nameBn: 'ট্রাক্টর ট্রান্সমিশন অয়েল',
      slug: 'tractor-transmission-oil',
      description: 'Specialized transmission oil for tractor gearboxes. Smooth gear shifting. Protects gears from wear and corrosion.',
      descriptionBn: 'ট্রাক্টর গিয়ারবক্সের জন্য বিশেষায়িত ট্রান্সমিশন অয়েল।',
      price: 620, priceUnit: 'LITRE', categoryId: lubeCat?.id,
      featured: false, inStock: true,
      images: [img('lubricants', 'Tractor-Transmission-Oil.png')],
      specs: { type: 'Transmission Oil', usage: 'Tractor Gearboxes', benefit: 'Smooth shifting' },
    },
    {
      name: 'Tractor Utto — Universal Oil',
      nameBn: 'ট্রাক্টর উটো',
      slug: 'tractor-utto',
      description: 'Universal tractor oil suitable for multiple applications. Can be used in engines, transmissions and hydraulic systems. Convenient all-in-one solution.',
      descriptionBn: 'একাধিক প্রয়োগের জন্য উপযুক্ত ইউনিভার্সাল ট্রাক্টর অয়েল।',
      price: 550, priceUnit: 'LITRE', categoryId: lubeCat?.id,
      featured: false, inStock: true,
      images: [img('lubricants', 'Tractor-Utto.png')],
      specs: { type: 'Universal Tractor Oil', usage: 'Engine, Transmission, Hydraulics', benefit: 'Multi-purpose' },
    },
  ];

  for (const p of products) {
    if (!p.categoryId) {
      console.warn(`  SKIPPED (no category): ${p.name}`);
      continue;
    }
    await prisma.product.create({
      data: {
        name: p.name,
        nameBn: p.nameBn,
        slug: p.slug,
        description: p.description,
        descriptionBn: p.descriptionBn,
        price: p.price,
        priceUnit: p.priceUnit,
        images: JSON.stringify(p.images),
        featured: p.featured ?? false,
        inStock: p.inStock ?? true,
        isActive: true,
        hidePrice: p.hidePrice ?? false,
        categoryId: p.categoryId,
        specs: JSON.stringify(p.specs || {}),
      },
    });
    console.log(`  Created: ${p.name}`);
  }

  console.log(`\nSeeded ${products.filter(p => p.categoryId).length} products successfully!`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
